"use client";
import { useState, useEffect } from "react";
import { ArrowUpRight, Plus, Upload, Search, Box, Download, FileText, Check } from "lucide-react";
import SpecificationEditor, {Choice,api,download} from '@/components/specification-editor';
import {newSpecification,type Specification,verificationIssues} from '@/lib/specification';
import {scheduleSpecifications} from '@/lib/schedule';
import {generateInWorker} from '@/lib/geometry/browser';
import {generateRhino} from '@/lib/geometry/engine.mjs';
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
const examples = [
 {name:"Form F stool",brand:"EKOMIA",category:"Furniture",image:"https://ekomia.de/cdn/shop/files/stool-form-f-oak-iso.jpg?v=1750687658&width=1200",source:"https://ekomia.de/en/products/hocker-form-f-eiche"},
 {name:"Sabinar pendant",brand:"EGLO",category:"Lighting",image:"https://onlinelighting.com.au/images/detailed/204/96981.jpg",source:"https://onlinelighting.com.au/sabinar-small-pendant-white-96981n.html"},
 {name:"Solid brass pull",brand:"SCHAUB",category:"Hardware",image:"https://schaubandcompany.com/products/732-03.jpg",source:"https://schaubandcompany.com/product_gallery.php?id=483"}
];
export default function Home(){
 const [category,setCategory]=useState("All"),[query,setQuery]=useState(""),[open,setOpen]=useState(false),[products,setProducts]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[files,setFiles]=useState<File[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[status,setStatus]=useState('All statuses'),[manufacturer,setManufacturer]=useState('All manufacturers'),[project,setProject]=useState('All projects'),[loading,setLoading]=useState(true);
 const refresh=()=>api('/api/products').then(setProducts).catch(e=>setError(e.message)).finally(()=>setLoading(false));
 useEffect(()=>{void refresh();const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'start_product_model',description:'Open a new specification for human review. Does not save or generate geometry.',inputSchema:{type:'object',properties:{product_name:{type:'string',maxLength:200}},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='product_name')||(input.product_name!==undefined&&(typeof input.product_name!=='string'||input.product_name.length>200)))throw Error('Invalid product name.');setSelected({...newSpecification(),product_name:input.product_name||'Untitled product'});setFiles([]);setOpen(true);return {opened:true};}},{signal:lifecycle.signal})).catch(console.error);return ()=>lifecycle.abort();},[]);
 const start=(reference?:typeof examples[number])=>{const s=newSpecification();if(reference){s.product_name=reference.name;s.manufacturer=reference.brand;s.category=reference.category as any;s.source_urls=[reference.source];s.image=reference.image;s.strategy=reference.category==='Lighting'?'unsupported':reference.category==='Hardware'?'pull':'stool';}setSelected(s);setFiles([]);setOpen(true);};
 const importSchedule=async(file:File)=>{setBusy('Importing schedule');setError('');let count=0;try{const items=scheduleSpecifications(await file.text());for(const s of items){await api('/api/products',s);count++;}await refresh();}catch(e){setError(`${e instanceof Error?e.message:'Import failed.'}${count?` ${count} items were saved before the failure.`:''}`);await refresh();}finally{setBusy('');}};
 const receiveFiles=(incoming:File[])=>{if(incoming.length===1&&incoming[0].name.toLowerCase().endsWith('.csv')){void importSchedule(incoming[0]);return;}setSelected(newSpecification());setFiles(incoming);setOpen(true);};
 const visible=products.filter(p=>(category==='All'||p.category===category)&&`${p.product_name} ${p.manufacturer} ${p.model_number}`.toLowerCase().includes(query.toLowerCase())&&(status==='All statuses'||p.status===status)&&(manufacturer==='All manufacturers'||p.manufacturer===manufacturer)&&(project==='All projects'||p.project===project));
 const exportBatch=async()=>{setBusy('Generating combined Rhino file');setError('');try{const eligible=visible.filter(p=>p.status==='Ready'&&!verificationIssues(p).length);if(!eligible.length)throw Error('Generate at least one reviewed model before batch export.');const result=await generateInWorker(eligible);download(result.bytes,'Formwork-schedule.3dm');}catch(e){setError(e instanceof Error?e.message:'Export failed.');}finally{setBusy('');}};
 return <div className="studio"><header><a className="wordmark" href="/">formwork<span>®</span></a><nav><a className="active" href="/">Model library</a><button onClick={()=>start()}>New model <Plus size={15}/></button></nav><div className="studio-name">DESIGN WORKSPACE <span className="avatar">FW</span></div></header>
 <main><div className="eyebrow">YOUR PRODUCT-TO-RHINO WORKSPACE</div><div className="page-heading"><div><h1>From reference.<br/><em>To ready.</em></h1><p>Considered geometry for the spaces you create.</p></div><div className="heading-note"><Box size={22}/><span>Real NURBS. Clean layers.<br/>Made for your Rhino workflow.</span></div></div>
 <section className="input-area" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();receiveFiles(Array.from(e.dataTransfer.files));}}><div className="upload-icon"><Upload size={25}/></div><div><h2>Start with a reference</h2><p>Drop a product image, specification, schedule, or paste a product URL</p><div className="input-types">JPG, PNG, WEBP <span>·</span> PDF <span>·</span> CSV <span>·</span> Product URL</div></div><button className="primary" onClick={()=>start()}>New model <Plus size={18}/></button></section>
 {error&&<div className="notice error" role="alert">{error}<button className="text-button" onClick={()=>{setError('');void refresh();}}>Retry library</button></div>}{busy&&<div className="notice" role="status">{busy}…</div>}
 <div className="section-heading"><h2>Model library <sup>{String(products.length).padStart(2,'0')}</sup></h2><div className="search"><Search size={16}/><input aria-label="Search products" placeholder="Search your library" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
 <div className="filter-row"><Tabs value={category} onValueChange={setCategory}><TabsList variant="line">{["All","Furniture","Lighting","Plumbing","Hardware","Equipment","Accessories"].map(x=><TabsTrigger key={x} value={x}>{x}</TabsTrigger>)}</TabsList></Tabs></div>
 <div className="library-tools"><div><Choice label="Status filter" value={status} onChange={setStatus} options={['All statuses','Needs Review','Ready']}/><Choice label="Manufacturer filter" value={manufacturer} onChange={setManufacturer} options={['All manufacturers',...new Set(products.map(p=>p.manufacturer).filter(Boolean))]}/><Choice label="Project filter" value={project} onChange={setProject} options={['All projects',...new Set(products.map(p=>p.project).filter(Boolean))]}/></div><div><label className="secondary schedule-upload"><Upload size={14}/>Import CSV<input type="file" accept=".csv" onChange={e=>{if(e.target.files?.[0])void importSchedule(e.target.files[0]);e.target.value='';}}/></label><button className="secondary" disabled={!!busy} onClick={exportBatch}><Download size={14}/>Export ready</button></div></div>
 {loading?<p className="body-muted">Loading your library…</p>:visible.length>0?<div className="product-grid">{visible.map(p=><button className="product-card" key={p.id} onClick={()=>{setSelected(p);setFiles([]);setOpen(true);}}><div className="product-image">{p.image?<img src={p.image} alt={p.product_name}/>:<div className="model-monogram"><Box size={64} strokeWidth={.6}/><span>{p.strategy.toUpperCase()}</span><strong>{p.dimensions.width.value??'—'} × {p.dimensions.depth.value??'—'} × {p.dimensions.height.value??'—'}</strong><small>mm</small></div>}<span className={`badge ${p.status==='Ready'?'ready':''}`}>{p.status==='Ready'&&<Check size={12}/>} {p.status}</span><span className="image-action"><ArrowUpRight size={19}/></span></div><div className="product-meta"><div className="eyebrow">{p.manufacturer||'CUSTOM PRODUCT'}</div><h3>{p.product_name}</h3><p>{p.category}<span>{p.project}</span></p></div></button>)}</div>:<div className="library-empty"><span>{products.length?'No products match these filters.':'Your next project starts here.'}</span><button className="text-button" onClick={()=>{const s=newSpecification();s.product_name='Studio table — sample';s.manufacturer='Formwork sample';s.notes='Demonstration specification, not a manufacturer product. All dimensions are explicit sample estimates.';for(const [k,v] of Object.entries({width:1200,depth:600,height:750,thickness:30,leg:40,inset:50}))s.dimensions[k]={value:v,classification:'Estimated',source:'Sample specification',evidence:'Demonstration only',approved:false};setSelected(s);setFiles([]);setOpen(true);}}>Try a sample specification <ArrowUpRight size={14}/></button></div>}
 <div className="collection-title"><div><h2>On the reference board</h2><p>Starting points to research. These are not verified models.</p></div><a href="/schedule-template.csv" download>Download schedule template <FileText size={14}/></a></div>
 <div className="product-grid">{examples.filter(p=>(category==="All"||category===p.category)&&`${p.name} ${p.brand}`.toLowerCase().includes(query.toLowerCase())).map((p,i)=><button className="product-card" key={p.name} onClick={()=>start(p)}><div className={`product-image image-${i}`}><img src={p.image} alt={p.name}/><span className="badge">Reference</span><span className="image-action"><ArrowUpRight size={19}/></span></div><div className="product-meta"><div className="eyebrow">{p.brand}</div><h3>{p.name}</h3><p>{p.category}<span>Review required</span></p></div></button>)}</div>
 <div className="library-foot"><span>Accurate by intention. Organized by material.</span><span>Millimeters · Z up · Front −Y</span></div></main><footer><span className="wordmark small">formwork</span><span>A better starting point for your next space.</span><span>RHINO .3DM / MM</span></footer>
 {open&&selected&&<SpecificationEditor key={selected.id} initial={selected} initialFiles={files} onClose={()=>setOpen(false)} onSaved={()=>{void refresh();}}/>}</div>
}
