"use client";
import {demoMode,demoApi,downloadDemoFile} from '@/lib/demo-storage';
import {useState} from 'react';
import {Plus,Check,Download,ArrowUpRight,FileText,Upload,Box} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {dimensionLabels,requiredDimensions,verificationIssues,type Specification} from '@/lib/specification';
import {generateInWorker} from '@/lib/geometry/browser';
import {generateRhino,planGeometry} from '@/lib/geometry/engine.mjs';

export function Choice({value,onChange,options,label}:{value:string,onChange:(v:string)=>void,options:string[],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>}
export async function api(path:string,body?:any){if(demoMode && path !== '/api/research')return demoApi(path,body);const response=await fetch(path,body?{method:'POST',...(body instanceof FormData?{body}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}:{});const data:any=await response.json();if(!response.ok)throw Error(data.error||'Request failed.');return data;}
export function download(bytes:Uint8Array,name:string){const blob=new Blob([new Uint8Array(bytes)],{type:'application/octet-stream'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function SpecificationEditor({initial,onClose,onSaved,initialFiles=[]}:{initial:Specification&{qa?:any,model_key?:string},onClose:()=>void,onSaved:()=>void,initialFiles?:File[]}){
 const [spec,setSpec]=useState(initial),[tab,setTab]=useState('references'),[url,setUrl]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[stage,setStage]=useState(initial.model_key?5:0),[qa,setQa]=useState<any>(initial.qa),[modelKey,setModelKey]=useState(initial.model_key),[pendingFiles,setPendingFiles]=useState(initialFiles);
 const update=(patch:Partial<Specification>)=>{setSpec(s=>({...s,...patch}));setQa(null);setModelKey(undefined);setStage(2);};
 const run=async(label:string,fn:()=>Promise<void>)=>{setBusy(label);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Operation failed.');}finally{setBusy('');}};
 const save=async()=>{await api('/api/products',spec);onSaved();};
 const upload=async(files:File[])=>{const documents=[...spec.source_documents];for(const file of files){const data=new FormData();data.set('file',file);documents.push(await api('/api/files',data));}update({source_documents:documents});setPendingFiles([]);};
 const research=()=>run('Inspecting sources',async()=>{setStage(1);let draft={...spec};if(url.trim()){const u=new URL(url.trim());if(u.protocol!=='https:')throw Error('Use an HTTPS product URL.');draft={...draft,source_urls:[...new Set([...draft.source_urls,u.href])]};}if(pendingFiles.length)throw Error('Upload the selected references before research.');const result=await api('/api/research',draft);setSpec(result);setUrl('');await api('/api/products',result);onSaved();setStage(2);setTab('specification');});
 const model=()=>run('Generating Rhino geometry',async()=>{const issues=verificationIssues(spec);if(issues.length)throw Error(issues.join(' '));planGeometry(spec);await save();setStage(3);const result=await generateInWorker([spec]);setStage(4);setQa(result.report);const form=new FormData();form.set('file',new File([new Uint8Array(result.bytes)],`${spec.product_name.replace(/[^a-z0-9_-]/gi,'_')}.3dm`));form.set('specification',JSON.stringify(spec));form.set('report',JSON.stringify(result.report));const saved=await api('/api/models',form);setModelKey(saved.key);setStage(5);setTab('qa');onSaved();});
 const issues=verificationIssues(spec);
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="editor"><div className="editor-title"><span className="eyebrow">PRODUCT WORKSPACE</span><DialogTitle>{spec.product_name}</DialogTitle><DialogDescription>Review the reference. Resolve the dimensions. Build with confidence.</DialogDescription></div>
 <ol className="workflow">{['Identify','Research','Verify','Model','QA','Ready'].map((s,i)=><li key={s} className={stage===i?'current':stage>i?'complete':''}><span>{stage>i?<Check size={13}/>:String(i+1).padStart(2,'0')}</span>{s}</li>)}</ol>
 {error&&<div role="alert" className="notice error">{error}</div>}{busy&&<div role="status" className="notice">{busy}…</div>}
 <Tabs value={tab} onValueChange={setTab}><TabsList variant="line"><TabsTrigger value="references">References</TabsTrigger><TabsTrigger value="specification">Specification</TabsTrigger><TabsTrigger value="qa">Geometry & QA</TabsTrigger></TabsList>
 <TabsContent value="references"><div className="editor-body"><h3>Start with what you have.</h3><p className="body-muted">Combine a product page with manufacturer drawings or photography. Uploaded manufacturer documentation takes priority.</p><label>Product URL<div className="url-row"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://manufacturer.com/product"/><button className="secondary" disabled={!!busy} onClick={()=>{try{const u=new URL(url);if(u.protocol!=='https:')throw Error();update({source_urls:[...new Set([...spec.source_urls,u.href])]});setUrl('');}catch{setError('Enter a valid HTTPS URL.');}}}>Add <Plus size={15}/></button></div></label>
 {spec.source_urls.map(u=><div className="source-row" key={u}><a href={u} target="_blank" rel="noreferrer">{u}<ArrowUpRight size={14}/></a><button aria-label={`Remove ${u}`} onClick={()=>update({source_urls:spec.source_urls.filter(x=>x!==u)})}>Remove</button></div>)}
 <label className="file-drop"><Upload size={23}/><strong>Add specification sheets or images</strong><span>PDF, JPG, PNG, WEBP, CSV, XLSX · up to 20 MB each</span><input type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.webp,.csv,.xlsx" onChange={e=>setPendingFiles(Array.from(e.target.files||[]))}/></label>
 {pendingFiles.length>0&&<div className="notice">{pendingFiles.map(f=>f.name).join(', ')}<button className="secondary" disabled={!!busy} onClick={()=>run('Uploading references',()=>upload(pendingFiles))}>Upload references</button></div>}
 {spec.source_documents.map(f=><a className="source-row" key={f.key} href={`/api/files?key=${encodeURIComponent(f.key)}`} onClick={demoMode ? e=>{e.preventDefault();downloadDemoFile(f.key).catch(e=>setError(e.message));} : undefined}><FileText size={16}/>{f.name}</a>)}
 <div className="notice">Image identification and document interpretation require a connected research provider. Without one, enter and cite dimensions manually. No dimensions are inferred silently.</div>
 <button className="primary" disabled={!!busy} onClick={research}>Research & review <ArrowUpRight size={16}/></button><button className="text-button" onClick={()=>{setStage(2);setTab('specification');}}>Enter specifications manually</button></div></TabsContent>
 <TabsContent value="specification"><div className="editor-body"><div className="form-grid">{(['manufacturer','product_name','model_number','variant','project','material','finish'] as const).map(k=><label key={k}>{({manufacturer:'Manufacturer',product_name:'Product name',model_number:'Model / SKU',variant:'Variant',project:'Project',material:'Material',finish:'Finish'})[k]}<input value={spec[k]} onChange={e=>update({[k]:e.target.value})}/></label>)}<label>Category<Choice value={spec.category} onChange={v=>update({category:v as any})} options={['Furniture','Lighting','Plumbing','Hardware','Equipment','Accessories']} label="Category"/></label><label>Geometry strategy<Choice value={spec.strategy} onChange={v=>{update({strategy:v as any});}} options={['table','stool','pull','unsupported']} label="Geometry strategy"/></label></div>
 <div className="notice">Supported geometry: rectangular top with four square legs, or a straight rectangular pull with two supports. Confirm this construction matches the product. Curved, angled, hollow, or sculptural products require a custom strategy.</div>
 {spec.research_notes.map((n,i)=><div className="research-note" key={i}>{n}</div>)}
 <div className="dimension-title"><h3>Dimensions</h3><span>Whole millimeters only</span></div><Table><TableHeader><TableRow><TableHead>Dimension</TableHead><TableHead>mm</TableHead><TableHead>Evidence class</TableHead><TableHead>Approval</TableHead></TableRow></TableHeader><TableBody>{requiredDimensions(spec.strategy).map(k=>{const d=spec.dimensions[k];return <TableRow key={k}><TableCell><strong>{dimensionLabels[k]}</strong><details><summary>Source & evidence</summary><input aria-label={`${dimensionLabels[k]} source`} placeholder="Document page / source URL / user measurement" value={d.source} onChange={e=>update({dimensions:{...spec.dimensions,[k]:{...d,source:e.target.value,approved:false}}})}/><textarea aria-label={`${dimensionLabels[k]} evidence`} placeholder="Quoted dimension, derivation, or estimate rationale" value={d.evidence} onChange={e=>update({dimensions:{...spec.dimensions,[k]:{...d,evidence:e.target.value,approved:false}}})}/></details></TableCell><TableCell><input className="dimension-input" type="number" min="1" max="20000" step="1" aria-label={dimensionLabels[k]} value={d.value??''} onChange={e=>update({dimensions:{...spec.dimensions,[k]:{...d,value:e.target.value===''?null:Number(e.target.value),approved:false}}})}/></TableCell><TableCell><Choice label={`${dimensionLabels[k]} classification`} value={d.classification} options={['Verified','Derived','Estimated']} onChange={v=>update({dimensions:{...spec.dimensions,[k]:{...d,classification:v as any,approved:false}}})}/></TableCell><TableCell><label className="check-label"><Checkbox checked={d.approved} onCheckedChange={v=>update({dimensions:{...spec.dimensions,[k]:{...d,approved:v===true}}})}/>{d.classification==='Estimated'?'Approve estimate':'Confirm'}</label></TableCell></TableRow>})}</TableBody></Table>
 <p className="body-muted">Verified: explicitly documented. Derived: calculated from documented dimensions. Estimated: user-approved approximation. Leg inset is measured from the outer edge to the outside of each leg.</p>
 {spec.cad_assets.length>0&&<section><h3>Existing CAD assets located</h3>{spec.cad_assets.map(a=><a className="source-row" key={a.url} href={a.url} target="_blank" rel="noreferrer">{a.label}<ArrowUpRight size={16}/></a>)}<p className="body-muted">Review these assets first. Automatic CAD cleanup is not supported in this version; the generator reconstructs the approved parametric specification.</p></section>}
 <label>Modeling notes<textarea value={spec.notes} onChange={e=>update({notes:e.target.value})} placeholder="Mounting conditions, finish notes, or unresolved questions"/></label>
 <div className="review-footer"><span>{issues.length?`${issues.length} review items remaining`:'All required dimensions approved'}</span><button className="primary" disabled={!!busy||issues.length>0} onClick={model}>Generate Rhino model <Box size={17}/></button></div></div></TabsContent>
 <TabsContent value="qa"><div className="editor-body">{qa?<><div className="qa-heading"><Check size={28}/><div><h3>Geometry checks passed.</h3><p>Reopened and inspected as a genuine Rhino file.</p></div></div><div className="qa-grid">{qa.checks.map((c:any)=><div key={c.label}><span><Check size={14}/>{c.label}</span><strong>{c.value}</strong></div>)}</div><p className="body-muted">Z up · Front −Y · {qa.products[0]?.insertion}. Estimates remain estimates after geometric QA.</p><div className="notice">{qa.products[0]?.approvedEstimates?.length||0} approved estimated dimensions. Check suitability for the intended design and coordination task.</div><p className="body-muted">{qa.scope}</p>{modelKey?<a className="primary download" href={`/api/files?key=${encodeURIComponent(modelKey)}`} onClick={demoMode ? e=>{e.preventDefault();downloadDemoFile(modelKey).catch(e=>setError(e.message));} : undefined}><Download size={17}/>Download .3dm</a>:<div className="notice">Geometry passed, but the file has not been saved. Retry generation to enable download.</div>}<button className="text-button" onClick={()=>download(new TextEncoder().encode(JSON.stringify(qa,null,2)),`${spec.product_name}-qa.json`)}>Download QA report</button></>:<div className="empty-state"><Box size={35}/><h3>Ready when your specification is.</h3><p>Approve the required dimensions to generate and inspect your model.</p><button className="secondary" onClick={()=>setTab('specification')}>Review specification</button></div>}</div></TabsContent></Tabs>
 <div className="editor-bottom"><span>MM / NURBS / RHINO 8</span><button className="secondary" disabled={!!busy} onClick={()=>run('Saving specification',save)}>Save specification</button></div>
 </DialogContent></Dialog>;
}
